# Generated by Django 4.0.5 on 2022-06-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwardss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(blank=True, max_length=65),
        ),
    ]
